### ISSUE TITLE
Error: [Upload component not initialised!]

### ISSUE THREAD

**Issue by psing008** [tomitrescak/meteor-uploads#96]
<h4>After clicking upload</h4>

<code>W20150528-20:38:25.927(-7)? (STDERR) Error: [Upload component not initialised!]</code>
<code> W20150528-20:38:25.927(-7)? (STDERR)  at Object.UploadServer.serve [as handle] (packages/tomi:upload-server/upload_server.js:134:1)</code>
<code>W20150528-20:38:25.928(-7)? (STDERR)     at next (/Users/AMG101/.meteor/packages/webapp/.1.2.0.gsy0oo++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
</code>

<code> W20150528-20:38:25.928(-7)? (STDERR)     at Function.app.handle (/Users/AMG101/.meteor/packages/webapp/.1.2.0.gsy0oo++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:198:3)
</code>

<code> W20150528-20:38:25.928(-7)? (STDERR)     at Object.fn [as handle] (/Users/AMG101/.meteor/packages/webapp/.1.2.0.gsy0oo++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:74:14)
</code>

<code>W20150528-20:38:25.928(-7)? (STDERR)     at next (/Users/AMG101/.meteor/packages/webapp/.1.2.0.gsy0oo++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
</code>

<code>W20150528-20:38:25.928(-7)? (STDERR)     at Object.WebAppInternals.staticFilesMiddleware (packages/webapp/webapp_server.js:331:1)
</code>

<code>W20150528-20:38:25.928(-7)? (STDERR)     at packages/webapp/webapp_server.js:625:1
</code>

<h4> Looking in chrome JavaScript console, it says it tried to make POST call http://localhost:3000/upload and returned a 500 error code</h4>

<h3> My UploadServer.init looks like this </h3>

     ' UploadServer.init({

      tmpDir: process.env.PWD + '/uploads/tmp',
      uploadDir: process.env.PWD + '/uploads/',
      getDirectory: function(fileInfo, formData) {
      if (formData && formData.directoryName != null) {
        return formData.directoryName;
      }
      return "";
    },

' finished: function(fileInfo, formData) {
      if (formData && formData._id != null) {
      //  Items.update({_id: formData._id}, { $push: { uploads: fileInfo }});
    }
  }'

,getFileName: function(fileInfo, formData) {
      if (formData && formData.prefix != null) {
        return formData.prefix + '_' + fileInfo.name;
      }
      return fileInfo.name;
    } })'

What am i doing wrong? I am on Mac OXS Yosemite, with lastest node and meteor

![screen shot 2015-05-28 at 9 00 09 pm](https://cloud.githubusercontent.com/assets/3147397/7876197/9304d0ac-057c-11e5-86c9-5e7a815ac577.png)

**Comment by psing008** [comment]
I fixeds this error by not using the command line and making the .upload folder manually.
checkCreateDirectory was thrown off by that.
